export interface FoodMeta {
  id: string;
  imagePath: string;
  cname: string;
  text?: string;
}

export const foods: FoodMeta[] = [
  {
    id: 'guoqiaomixian',
    imagePath: '/images/food/guoqiaomixian.webp',
    cname: '过桥米线',
    text: '爱情一线牵，烫嘴也甘愿',
  },
  {
    id: 'hongyouchaoshou',
    imagePath: '/images/food/hongyouchaoshou.webp',
    cname: '红油抄手',
    text: '皮薄馅多，像前任，辣到泪崩',
  },
  {
    id: 'huangmenjimifan',
    imagePath: '/images/food/huangmenjimifan.webp',
    cname: '黄焖鸡米饭',
    text: '鸡在锅里焖，我在工位熬',
  },
  {
    id: 'luosifen',
    imagePath: '/images/food/luosifen.webp',
    cname: '螺蛳粉',
    text: '嗦粉三分钟，同事失联三小时',
  },
  {
    id: 'malatang',
    imagePath: '/images/food/malatang.webp',
    cname: '麻辣烫',
    text: '选菜如选妃，辣度决定朕的心情',
  },
  {
    id: 'pidanshourouzhou',
    imagePath: '/images/food/pidanshourouzhou.webp',
    cname: '皮蛋瘦肉粥',
    text: '一碗下肚，今天又被世界轻轻抱住',
  },
  {
    id: 'suanlatudousi',
    imagePath: '/images/food/suanlatudousi.webp',
    cname: '酸辣土豆丝',
    text: '酸辣一相逢，米饭便成空',
  },
  {
    id: 'xiaolongbao',
    imagePath: '/images/food/xiaolongbao.webp',
    cname: '小笼包',
    text: '先开窗，再喝汤，人生别急着莽',
  },
  {
    id: 'zhaji',
    imagePath: '/images/food/zhaji.webp',
    cname: '炸鸡',
    text: '卡路里警报？炸鸡说先吃再说',
  },
  {
    id: 'zhujiaofan',
    imagePath: '/images/food/zhujiaofan.webp',
    cname: '猪脚饭',
    text: '补胶原不补简历',
  },
  {
    id: 'baiqieji',
    imagePath: '/images/food/baiqieji.webp',
    cname: '白切鸡',
    text: '生活太淡，蘸点酱油再躺',
  },
  {
    id: 'baozaifan',
    imagePath: '/images/food/baozaifan.webp',
    cname: '煲仔饭',
    text: '锅巴焦了，理想还是生的',
  },
  {
    id: 'chaofan',
    imagePath: '/images/food/chaofan.webp',
    cname: '炒饭',
    text: '翻锅一万次，翻不动房租',
  },
  {
    id: 'chashaofan',
    imagePath: '/images/food/chashaofan.webp',
    cname: '叉烧饭',
    text: '甜到发腻，像老板的承诺',
  },
  {
    id: 'chongqingxiaomian',
    imagePath: '/images/food/chongqingxiaomian.webp',
    cname: '重庆小面',
    text: '辣哭算排毒，钱包不许哭',
  },
  {
    id: 'dapanji',
    imagePath: '/images/food/dapanji.webp',
    cname: '大盘鸡',
    text: '我要的是大盘鸡，不是大盘土豆',
  },
  {
    id: 'disanxian',
    imagePath: '/images/food/disanxian.webp',
    cname: '地三鲜',
    text: '没肉也能香，像极了爱情',
  },
  {
    id: 'douzhi',
    imagePath: '/images/food/douzhi.webp',
    cname: '老北京豆汁儿',
    text: '谁喝谁知道！',
  },
  {
    id: 'hongshaorou',
    imagePath: '/images/food/hongshaorou.webp',
    cname: '红烧肉',
    text: '肥而不腻，是肉；腻而不富，是我',
  },
  {
    id: 'hongshaosizitou',
    imagePath: '/images/food/hongshaosizitou.webp',
    cname: '红烧狮子头',
    text: '像同事，一夹就散',
  },
  {
    id: 'hulatang',
    imagePath: '/images/food/hulatang.webp',
    cname: '胡辣汤',
    text: '晨市灵魂，喝完继续困',
  },
  {
    id: 'huoguo',
    imagePath: '/images/food/huoguo.webp',
    cname: '火锅',
    text: '涮别人牛肉，煮自己前途',
  },
  {
    id: 'lajiaochaorou',
    imagePath: '/images/food/lajiaochaorou.webp',
    cname: '辣椒炒肉',
    text: '肉少辣多，像工资，刺激但不够饱',
  },
  {
    id: 'luroufan',
    imagePath: '/images/food/luroufan.webp',
    cname: '卤肉饭',
    text: '勺子一拌，焦虑减半',
  },
  {
    id: 'mapodoufu',
    imagePath: '/images/food/mapodoufu.webp',
    cname: '麻婆豆腐',
    text: '麻得嘴颤，像面对绩效的我',
  },
  {
    id: 'pisa',
    imagePath: '/images/food/pisa.webp',
    cname: '披萨',
    text: '芝士拉丝，像工作日，越拉越长',
  },
  {
    id: 'shousi',
    imagePath: '/images/food/shousi.webp',
    cname: '寿司',
    text: '冷得精致，像没温度的KPI',
  },
  {
    id: 'shousikaoya',
    imagePath: '/images/food/shousikaoya.webp',
    cname: '手撕烤鸭',
    text: '健身餐？不了，我练的是手撕鸭腱子肉',
  },
  {
    id: 'suantangyu',
    imagePath: '/images/food/suantangyu.webp',
    cname: '酸汤鱼',
    text: '今日份内卷：鱼在汤里扑腾，我在工位复读',
  },
  {
    id: 'wuhanreganmian',
    imagePath: '/images/food/wuhanreganmian.webp',
    cname: '武汉热干面',
    text: '别拌了，再拌我就成职场老油条了',
  },
  {
    id: 'xiajiao',
    imagePath: '/images/food/xiajiao.webp',
    cname: '虾饺',
    text: '别戳破那层皮，戳破就是打工人的薪资保密协议',
  },
  {
    id: 'xihucuyu',
    imagePath: '/images/food/xihucuyu.webp',
    cname: '西湖醋鱼',
    text: '吃一口，酸到皱眉——爱情模拟器启动',
  },
  {
    id: 'banshuzhishi',
    imagePath: '/images/food/banshuzhishi.webp',
    cname: '半熟芝士',
    text: '半熟芝士，不熟不透最迷人',
  },
  {
    id: 'chaoxianlengmian',
    imagePath: '/images/food/chaoxianlengmian.webp',
    cname: '朝鲜冷面',
    text: '朝鲜冷面，冰爽人生不设限',
  },
  {
    id: 'chuanchuanxiang',
    imagePath: '/images/food/chuanchuanxiang.webp',
    cname: '串串香',
    text: '串起烟火，烫出青春',
  },
  {
    id: 'ganchaoniuhe',
    imagePath: '/images/food/ganchaoniuhe.webp',
    cname: '干炒牛河',
    text: '每一口都是生活的奔波',
  },
  {
    id: 'guandongzhu',
    imagePath: '/images/food/guandongzhu.webp',
    cname: '关东煮',
    text: '吃关东煮，没个主角命，都是配角',
  },
  {
    id: 'huiguorou',
    imagePath: '/images/food/huiguorou.webp',
    cname: '回锅肉',
    text: '肉都回锅了，你还不回头？',
  },
  {
    id: 'huntun',
    imagePath: '/images/food/huntun.webp',
    cname: '馄饨',
    text: '就是皮儿有点 “薄情”',
  },
  {
    id: 'jianbingguozi',
    imagePath: '/images/food/jianbingguozi.webp',
    cname: '煎饼果子',
    text: '呦呦，切克闹',
  },
  {
    id: 'laziji',
    imagePath: '/images/food/laziji.webp',
    cname: '辣子鸡',
    text: '辣得人想逃离，可又舍不得',
  },
  {
    id: 'makalong',
    imagePath: '/images/food/makalong.webp',
    cname: '马卡龙',
    text: '马卡龙好看，就像生活的虚假繁荣',
  },
  {
    id: 'maoxuewang',
    imagePath: '/images/food/maoxuewang.webp',
    cname: '毛血旺',
    text: '旺了菜，咋不旺我的钱包呢',
  },
  {
    id: 'meicaikourou',
    imagePath: '/images/food/meicaikourou.webp',
    cname: '梅菜扣肉',
    text: '咋就给我上个盘子啊？',
  },
  {
    id: 'shuangpinai',
    imagePath: '/images/food/shuangpinai.webp',
    cname: '双皮奶',
    text: '一层不够，两层来凑，胖也不愁',
  },
  {
    id: 'shufuleisongbing',
    imagePath: '/images/food/shufuleisongbing.webp',
    cname: '舒芙蕾松饼',
    text: '颜值高又如何，还不是进肚子',
  },
  {
    id: 'suanrongshenghao',
    imagePath: '/images/food/suanrongshenghao.webp',
    cname: '蒜蓉生蚝',
    text: '蚝好贵，生活好累',
  },
  {
    id: 'tilamisu',
    imagePath: '/images/food/tilamisu.webp',
    cname: '提拉米苏',
    text: '再怎么提拉，也提不起我的精气神',
  },
  {
    id: 'xiaochaohuangniurou',
    imagePath: '/images/food/xiaochaohuangniurou.webp',
    cname: '小炒黄牛肉',
    text: '牛肉小炒，工资也小 “炒”',
  },
  {
    id: 'xihongshichaojidan',
    imagePath: '/images/food/xihongshichaojidan.webp',
    cname: '西红柿炒鸡蛋',
    text: '据说这玩意是溥仪发明的？',
  },
  {
    id: 'ganbiandoujiao',
    imagePath: '/images/food/ganbiandoujiao.webp',
    cname: '干煸豆角',
    text: '豆角干煸，越干越鲜',
  },
  {
    id: 'guobaorou',
    imagePath: '/images/food/guobaorou.webp',
    cname: '锅包肉',
    text: '人生苦短，肉要趁热吃',
  },
  {
    id: 'hongshaoqiezi',
    imagePath: '/images/food/hongshaoqiezi.webp',
    cname: '红烧茄子',
    text: '再佛系，下油锅也得红得发紫',
  },
  {
    id: 'huangguachaojidan',
    imagePath: '/images/food/huangguachaojidan.webp',
    cname: '黄瓜炒鸡蛋',
    text: '本菜启示：别卷，越炒越缩水',
  },
  {
    id: 'huojimian',
    imagePath: '/images/food/huojimian.webp',
    cname: '火鸡面',
    text: '辣得诚实，不骗眼泪，只骗你买牛奶',
  },
  {
    id: 'jidangeng',
    imagePath: '/images/food/jidangeng.webp',
    cname: '鸡蛋羹',
    text: '内卷失败，选择躺平成“蛋界布丁”',
  },
  {
    id: 'kuguachaojidan',
    imagePath: '/images/food/kuguachaojidan.webp',
    cname: '苦瓜炒鸡蛋',
    text: '长大的标志就是，开始爱吃苦瓜鸡蛋了',
  },
  {
    id: 'baobeijingsuanyangrou',
    imagePath: '/images/food/baobeijingsuanyangrou.webp',
    cname: '老北京涮羊肉',
    text: '肉片秒过水，比打工人下班还快',
  },
  {
    id: 'niupai',
    imagePath: '/images/food/niupai.webp',
    cname: '牛排',
    text: '我就爱吃十分熟的',
  },
  {
    id: 'roubaozi',
    imagePath: '/images/food/roubaozi.webp',
    cname: '肉包子',
    text: '我是隔壁小笼包的哥哥',
  },
  {
    id: 'shaoji',
    imagePath: '/images/food/shaoji.webp',
    cname: '烧鸡',
    text: '先被炙烤再被拆解，像极了项目流程',
  },
  {
    id: 'shaxianyatuifan',
    imagePath: '/images/food/shaxianyatuifan.webp',
    cname: '沙县鸭腿饭',
    text: '鸭鸭走了，腿还陪你加班',
  },
  {
    id: 'shengjianbao',
    imagePath: '/images/food/shengjianbao.webp',
    cname: '生煎包',
    text: '包子会煎，我连翻身都不会',
  },
  {
    id: 'shucaishala',
    imagePath: '/images/food/shucaishala.webp',
    cname: '熟菜沙拉',
    text: '爸妈问我为什么在吃草',
  },
  {
    id: 'shuizhuniurou',
    imagePath: '/images/food/shuizhuniurou.webp',
    cname: '水煮牛肉',
    text: '辣到上头，才懂职场比花椒更麻',
  },
  {
    id: 'suanrongfanshuye',
    imagePath: '/images/food/suanrongfanshuye.webp',
    cname: '蒜蓉番薯叶',
    text: '吃最便宜的绿，交最贵的房租',
  },
  {
    id: 'tangcupaigu',
    imagePath: '/images/food/tangcupaigu.webp',
    cname: '糖醋排骨',
    text: '啃完排骨，继续啃项目的硬骨头',
  },
  {
    id: 'xiaojidunmogu',
    imagePath: '/images/food/xiaojidunmogu.webp',
    cname: '小鸡炖蘑菇',
    text: '一锅慢炖，像我升职——咕嘟咕嘟没动静',
  },
  {
    id: 'xiqinhuashengmi',
    imagePath: '/images/food/xiqinhuashengmi.webp',
    cname: '西芹花生米',
    text: 'KPI暴涨，吃块芹菜降降压',
  },
];
